version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: htn_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hackathon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: htn_backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/hackathon
    volumes:
      - .:/app
      - /app/node_modules
    command:
      [
        "sh",
        "-c",
        "npx prisma migrate deploy && npx ts-node src/seed.ts && npm run dev",
      ]

volumes:
  postgres_data:
